In [ ]:
import pandas as pd

# load the data from the URL
url = "https://raw.githubusercontent.com/sudarshan-koirala/Salary-Prediciton-based-on-Years-of-Experience/master/Salary_Data.csv"
data = pd.read_csv(url)

#display the first few rows of the dataset
print("First few rows of the dataset : ")
print(data.head())

First few rows of the dataset :
   YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [ ]:
# Display basic information about the dataset
print("\nBasic information about the dataset:")
print(data.info())

Basic information about the dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   YearsExperience  30 non-null     float64
 1   Salary           30 non-null     float64
dtypes: float64(2)
memory usage: 608.0 bytes
None

In [ ]:
# Display summary statistics of numerical columns
print("\nSummary statistics of numerical columns:")
print(data.describe())

Summary statistics of numerical columns:
       YearsExperience         Salary
count        30.000000      30.000000
mean          5.313333   76003.000000
std           2.837888   27414.429785
min           1.100000   37731.000000
25%           3.200000   56720.750000
50%           4.700000   65237.000000
75%           7.700000  100544.750000
max          10.500000  122391.000000

In [ ]:
# Display the shape of the dataset (number of rows and colums)
print("\nShape of the dataset:")
print(data.shape)

Shape of the dataset:
(30, 2)

In [ ]:
# Display datatypes of each column
print("\nData types of each column:")
print(data.dtypes)

Data types of each column:
YearsExperience    float64
Salary             float64
dtype: object

In [ ]:
#checking for missing values
print("\nMissing values in the dataset")
print(data.isnull().sum())

Missing values in the dataset
YearsExperience    0
Salary             0
dtype: int64

In [ ]:
#checking for duplicate values
print("\nMissing values in the dataset")
print(data.duplicated().sum())

Missing values in the dataset
0

In [ ]:
#remove duplicates if any
data = data.drop_duplicates()

In [ ]:
#rename columns if needed
data = data.rename(columns={"YearsExperience":"Exp"})

In [ ]:
#convert data types if needed
data["Exp"]=data["Exp"].astype(int)
data.head()

   Exp   Salary  Salary_in_thousands  Exp_in_months
0    1  39343.0               39.343             12
1    1  46205.0               46.205             12
2    1  37731.0               37.731             12
3    2  43525.0               43.525             24
4    2  39891.0               39.891             24

In [ ]:
#Selecting a single column
print("\nSelecting a single column : ")
print(data["Exp"])

Selecting a single column :
0      1
1      1
2      1
3      2
4      2
5      2
6      3
7      3
8      3
9      3
10     3
11     4
12     4
13     4
14     4
15     4
16     5
17     5
18     5
19     6
20     6
21     7
22     7
23     8
24     8
25     9
26     9
27     9
28    10
29    10
Name: Exp, dtype: int64

In [ ]:
#Selecting multiple colums
print("\nSelecting a single column : ")
print(data[["Exp","Salary"]])

Selecting a single column :
    Exp    Salary
0     1   39343.0
1     1   46205.0
2     1   37731.0
3     2   43525.0
4     2   39891.0
5     2   56642.0
6     3   60150.0
7     3   54445.0
8     3   64445.0
9     3   57189.0
10    3   63218.0
11    4   55794.0
12    4   56957.0
13    4   57081.0
14    4   61111.0
15    4   67938.0
16    5   66029.0
17    5   83088.0
18    5   81363.0
19    6   93940.0
20    6   91738.0
21    7   98273.0
22    7  101302.0
23    8  113812.0
24    8  109431.0
25    9  105582.0
26    9  116969.0
27    9  112635.0
28   10  122391.0
29   10  121872.0

In [ ]:
# Filtering rows based on a condition
print("\nFiltering rows based on a condition:")
print(data[data["Exp"] <5])

Filtering rows based on a condition:
    Exp   Salary
0     1  39343.0
1     1  46205.0
2     1  37731.0
3     2  43525.0
4     2  39891.0
5     2  56642.0
6     3  60150.0
7     3  54445.0
8     3  64445.0
9     3  57189.0
10    3  63218.0
11    4  55794.0
12    4  56957.0
13    4  57081.0
14    4  61111.0
15    4  67938.0

In [ ]:
#Adding new column
data["Salary_in_thousands"] = data["Salary"]/1000
data["Exp_in_months"] = data["Exp"] * 12
data.head()

   Exp   Salary  Salary_in_thousands  Exp_in_months
0    1  39343.0               39.343             12
1    1  46205.0               46.205             12
2    1  37731.0               37.731             12
3    2  43525.0               43.525             24
4    2  39891.0               39.891             24

In [ ]:
#Grouping data by a column and calculating statistics
#calculating the average salary for each years of experience
grouped_data = data.groupby("Exp_in_months").mean()
print("\ngrouped data - Average salary for each years of experience: ")
print(grouped_data)

grouped data - Average salary for each years of experience:
                Exp         Salary  Salary_in_thousands
Exp_in_months
12              1.0   41093.000000            41.093000
24              2.0   46686.000000            46.686000
36              3.0   59889.400000            59.889400
48              4.0   59776.200000            59.776200
60              5.0   76826.666667            76.826667
72              6.0   92839.000000            92.839000
84              7.0   99787.500000            99.787500
96              8.0  111621.500000           111.621500
108             9.0  111728.666667           111.728667
120            10.0  122131.500000           122.131500

In [ ]:
#reshaping data (pivot table, melt, stack, unstack)
#pivot table to calculate the average salary for each years of experience
pivot_table=data.pivot_table(index="Exp",values="Salary_in_thousands",aggfunc="mean")
print(pivot_table)

     Salary_in_thousands
Exp
1              41.093000
2              46.686000
3              59.889400
4              59.776200
5              76.826667
6              92.839000
7              99.787500
8             111.621500
9             111.728667
10            122.131500

In [ ]:
#Removing a column
#data = data.drop(columns=["Exp_in_months"])
data.head()
data1=data.to_csv("Salary_Data.csv")